# Generated by Django 5.2.5 on 2025-09-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_alter_user_affiliation_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
