# Generated by Django 5.2.5 on 2025-09-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file_url', models.URLField()),
                ('abstract', models.TextField(blank=True)),
                ('article_type', models.CharField(choices=[('regular', 'Regular'), ('poster', 'Poster')], max_length=10)),
                ('status', models.CharField(default='in_reception', max_length=20)),
            ],
        ),
    ]
