# Generated by Django 5.2.5 on 2025-10-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('main_file_url', models.URLField()),
                ('status', models.CharField(choices=[('reception', 'Recepción'), ('bidding', 'Bidding'), ('assignment', 'Asignación'), ('review', 'Revisión'), ('selection', 'Selección'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='reception', max_length=20)),
                ('article_type', models.CharField(choices=[('regular', 'Regular'), ('poster', 'Poster')], max_length=10)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('source_file_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
