# Generated by Django 5.2.5 on 2025-10-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='main_file_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='source_file_url',
        ),
        migrations.AddField(
            model_name='article',
            name='main_file',
            field=models.FileField(default='', upload_to='articles/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='articles/sources/'),
        ),
    ]
