# Generated by Django 5.2.5 on 2025-09-25 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='file_url',
            new_name='main_file_url',
        ),
        migrations.AddField(
            model_name='article',
            name='source_file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='notification_author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_article', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('reception', 'Recepción'), ('bidding', 'Bidding'), ('assignment', 'Asignación'), ('review', 'Revisión'), ('selection', 'Selección'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='reception', max_length=20),
        ),
    ]
