# Generated by Django 5.2.5 on 2025-10-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_file_url_article_main_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='session_name',
            field=models.CharField(default='General', max_length=200),
        ),
    ]
