# Generated by Django 5.2.6 on 2025-09-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('vista', models.CharField(choices=[('single blind', 'Single blind'), ('double blind', 'Double blind'), ('completo', 'Completo')], default='completo', max_length=12)),
            ],
        ),
    ]
