# Generated by Django 5.2.8 on 2025-11-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('blind_kind', models.CharField(choices=[('single blind', 'Single blind'), ('double blind', 'Double blind'), ('completo', 'Completo')], default='completo', max_length=12)),
            ],
        ),
    ]
