# Generated by Django 5.2.5 on 2025-10-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='blind_kind',
            field=models.CharField(choices=[('single blind', 'Single blind'), ('double blind', 'Double blind'), ('completo', 'Completo')], default='completo', max_length=12),
        ),
        migrations.AlterField(
            model_name='conference',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='conference',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]