# Generated by Django 5.2.6 on 2025-10-16 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_alter_conference_blind_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='chairs',
            field=models.ManyToManyField(blank=True, related_name='conferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
