# Generated by Django 5.2.5 on 2025-10-24 17:05

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_conference_chairs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='conference',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='unique_conference_title_ci'),
        ),
    ]
