# Generated by Django 4.2 on 2025-10-20 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference_session', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('main_file', models.FileField(upload_to='articles/')),
                ('status', models.CharField(choices=[('reception', 'Recepción'), ('bidding', 'Bidding'), ('assignment', 'Asignación'), ('review', 'Revisión'), ('selection', 'Selección'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='reception', max_length=20)),
                ('type', models.CharField(choices=[('regular', 'Regular'), ('poster', 'Poster')], max_length=10)),
                ('abstract', models.TextField(max_length=300)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='articles/sources/')),
                ('authors', models.ManyToManyField(related_name='article', to=settings.AUTH_USER_MODEL)),
                ('corresponding_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_article', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='conference_session.session')),
            ],
        ),
    ]
