# Generated by Django 5.2.7 on 2025-10-26 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='last_updated_after_publication',
        ),
        migrations.RemoveField(
            model_name='review',
            name='published_at',
        ),
    ]
