# Generated by Django 5.2.5 on 2025-10-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_remove_review_last_updated_after_publication_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignmentReview',
        ),
    ]
