# Generated by Django 5.2.5 on 2025-11-13 15:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0002_initial'),
        ('reviewer', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='article',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='review_assignment',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='chair.reviewassignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ReviewVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(3)])),
                ('opinion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='reviewer.review')),
            ],
        ),
    ]
