# Generated by Django 5.2.5 on 2025-10-26 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_scores', to='article.article')),
            ],
            options={
                'verbose_name_plural': 'review_scores',
            },
        ),
    ]
