# Generated by Django 5.2.5 on 2025-10-25 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_scores', to='article.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'review_scores',
                'unique_together': {('user', 'article')},
            },
        ),
    ]
