# Generated by Django 5.2.5 on 2025-10-28 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_score', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewscore',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
