# Generated by Django 5.2.5 on 2025-09-23 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('users', '0002_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('puntaje', models.IntegerField(choices=[(-3, -3), (-2, -2), (-1, -1), (0, 0), (1, 1), (2, 2), (3, 3)])),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisado', models.BooleanField(default=False)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'unique_together': {('revisor', 'articulo')},
            },
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interes', models.CharField(choices=[('interesado', 'Interesado'), ('quizas', 'Quizás'), ('no_interesado', 'No Interesado'), ('ninguno', 'Ninguno')], default='ninguno', max_length=20)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='articles.article')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='users.user')),
            ],
            options={
                'unique_together': {('revisor', 'articulo')},
            },
        ),
    ]
