# Generated by Django 5.2.5 on 2025-09-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('chairs', '0002_alter_assignmentreview_revisor'),
        ('users', '0002_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentreview',
            old_name='articulo',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='assignmentreview',
            old_name='revisado',
            new_name='reviewed',
        ),
        migrations.RenameField(
            model_name='assignmentreview',
            old_name='revisor',
            new_name='reviewer',
        ),
        migrations.RenameField(
            model_name='bidding',
            old_name='articulo',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='bidding',
            old_name='interes',
            new_name='interest',
        ),
        migrations.RenameField(
            model_name='bidding',
            old_name='revisor',
            new_name='reviewer',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='articulo',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='revisor',
            new_name='reviewer',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='puntaje',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='texto',
            new_name='text',
        ),
        migrations.AlterUniqueTogether(
            name='assignmentreview',
            unique_together={('reviewer', 'article')},
        ),
        migrations.AlterUniqueTogether(
            name='bidding',
            unique_together={('reviewer', 'article')},
        ),
    ]
