# Generated by Django 5.2.5 on 2025-10-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairs', '0003_rename_articulo_assignmentreview_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentreview',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
