# Generated by Django 5.2.5 on 2025-10-12 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('chairs', '0004_assignmentreview_is_active'),
        ('users', '0002_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bidding',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='article',
        ),
        migrations.RemoveField(
            model_name='bidding',
            name='reviewer',
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(choices=[('interested', 'Interesado'), ('maybe', 'Quizás'), ('not_interested', 'No Interesado'), ('none', 'Ninguno')], default='none', max_length=20)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='articles.article')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='users.user')),
            ],
            options={
                'unique_together': {('reviewer', 'article')},
            },
        ),
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_reviews', to='users.user')),
            ],
            options={
                'unique_together': {('reviewer', 'article')},
            },
        ),
        migrations.DeleteModel(
            name='AssignmentReview',
        ),
        migrations.DeleteModel(
            name='Bidding',
        ),
    ]
