# Generated by Django 5.2.6 on 2025-10-22 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='improvement_threshold',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='threshold_percentage',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
