# Generated by Django 5.2.8 on 2025-11-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_session', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='locked_selection',
            field=models.BooleanField(blank=True, default=False, help_text='If true, the selection type cannot be modified.'),
        ),
        migrations.AddField(
            model_name='session',
            name='type_selection',
            field=models.CharField(blank=True, choices=[('ScoreThresholdSelection', 'ScoreThresholdSelection'), ('CutoffSelection', 'CutoffSelection')], help_text='Type of selection used for this session.', max_length=50, null=True),
        ),
    ]
