# Generated by Django 5.2.6 on 2025-10-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_session', '0002_session_improvement_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='deadline',
            field=models.DateField(),
        ),
    ]
