# Generated by Django 5.2.5 on 2025-11-06 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_session', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='improvement_threshold',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
