# Generated by Django 5.2.6 on 2025-10-22 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_session', '0003_alter_session_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='chairs',
            field=models.ManyToManyField(blank=True, related_name='session', to=settings.AUTH_USER_MODEL),
        ),
    ]
