# Generated by Django 5.2.5 on 2025-10-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_session', '0004_session_chairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
