# Generated by Django 5.2.5 on 2025-10-24 17:05

import django.core.validators
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_alter_conference_title_and_more'),
        ('conference_session', '0005_alter_session_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='improvement_threshold',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='session',
            name='threshold_percentage',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='unique_session_title_ci'),
        ),
    ]
