# Generated by Django 5.2.5 on 2025-10-28 02:13

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_alter_conference_title_and_more'),
        ('conference_session', '0006_alter_session_improvement_threshold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='session',
            name='unique_session_title_ci',
        ),
        migrations.AlterField(
            model_name='session',
            name='chairs',
            field=models.ManyToManyField(blank=True, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='conference.conference'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('conference'), name='unique_session_title_per_conference_ci'),
        ),
    ]
