# Generated by Django 5.2.5 on 2025-10-28 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_alter_conference_title_and_more'),
        ('conference_session', '0007_remove_session_unique_session_title_ci_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='chairs',
            field=models.ManyToManyField(blank=True, related_name='session', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='conference.conference'),
        ),
    ]
