# Generated by Django 5.2.5 on 2025-10-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0005_alter_article_notification_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField()),
                ('conference_title', models.CharField(blank=True, max_length=255, null=True)),
                ('articles', models.ManyToManyField(related_name='conference_sessions', to='articles.article')),
            ],
        ),
    ]
