# Generated by Django 5.2.5 on 2025-09-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
    ]
